seed = 0
function = "_bin.model.main"
n_trials = 100

[sampler]
n_startup_trials = 20

[space]
seed = 0
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[space.data]
cache = true
path = "data/classif-num-medium-0-wine"
num_policy = "noisy-quantile"

[space.optimizer]
type = "Adam"
lr = [
    "_tune_",
    "loguniform",
    0.0003,
    0.01,
]

[space.model]
arch_type = "plain"

[space.model.backbone]
type = "BMoE"
n_blocks = [
    "_tune_",
    "int",
    1,
    6,
]
d_block = [
    "_tune_",
    "int",
    128,
    1280,
    64,
]
dropout = 0.0
d_block_per_expert = [
    "_tune_",
    "int",
    32,
    64,
    32,
]
gating_prior_std = [
    "_tune_",
    "uniform",
    0.1,
    1.0,
]
kl_factor = [
    "_tune_",
    "loguniform",
    0.001,
    1.0,
]
default_num_samples = 5
gating_type = "bayesian"
