seed = 0
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-large-0-nyc-taxi-green-dec-2016"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0005349697680311934
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 1216
dropout = 0.3469367839197159
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 119
