seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-4-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0002506670575009958
weight_decay = 0.0006786021134628937

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 1
d_block = 256
dropout = 0.36585066588647763
d_block_per_expert = 32
adapter = true
gating_type = "sigmoid_adapter"
