seed = 5
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/churn"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.0020554062603827007
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "DeepBMoE"
n_blocks = 3
d_block = 640
dropout = 0.0
d_block_per_expert = 64
default_num_samples = 10
tau = 2.9091569012525733
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 102
