seed = 0
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-3-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00040170258459524736
weight_decay = 0.0003308263076395297

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 1280
dropout = 0.0
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 40
