seed = 0
function = "_bin.model.main"
n_trials = 100

[sampler]
n_startup_trials = 20

[space]
seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[space.data]
cache = true
path = "data/regression-cat-medium-4-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    0.0003,
    0.01,
]
weight_decay = [
    "_tune_",
    "?loguniform",
    0.0,
    0.0001,
    0.1,
]

[space.model]
arch_type = "plain"

[space.model.backbone]
type = "BMoE"
n_blocks = [
    "_tune_",
    "int",
    1,
    6,
]
d_block = [
    "_tune_",
    "int",
    128,
    1280,
    64,
]
dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.5,
]
d_block_per_expert = [
    "_tune_",
    "int",
    32,
    64,
    32,
]
adapter = true
gating_type = "sigmoid_adapter_kmeans"
