seed = 0
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-wine_quality"
num_policy = "noisy-quantile"

[optimizer]
type = "Adam"
lr = 0.0003358024248846698

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 4
d_block = 896
dropout = 0.0
d_block_per_expert = 64
gating_prior_std = 0.7913792539959965
kl_factor = 0.7796737397863447
default_num_samples = 5
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 105
