seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-Ailerons"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.006089559151838404
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 1
d_block = 704
dropout = 0.36787500898946535
d_block_per_expert = 64
default_num_samples = 10
tau = 2.275796329509466
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 36
