seed = 0
function = "bin.model.main"
n_trials = 100

[sampler]
n_startup_trials = 20

[space]
seed = 0
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[space.data]
cache = true
path = "data/higgs-small"
num_policy = "noisy-quantile"

[space.optimizer]
type = "AdamW"
lr = ["_tune_", "loguniform", 0.0003, 0.01]
weight_decay = ["_tune_", "?loguniform", 0.0, 0.0001, 0.1]

[space.model]
arch_type = "plain"

[space.model.backbone]
type = "MoE"
n_blocks = ["_tune_", "int", 1, 3]
d_block = ["_tune_", "int", 128, 2048, 32]
num_experts = [
    "_tune_",
    "int",
    4,
    40,
    4,
]
gating_type = 'standard'
gating_prior_std = 1.0
kl_factor = 1e-2
dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.5,
]
device='cuda'