seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-analcatdata_supreme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0005016682402118049
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 5
d_block = 896
dropout = 0.0
d_block_per_expert = 32
default_num_samples = 10
tau = 0.6584574619979138
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 59
