seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/california"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.00034980918006525364
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 512
dropout = 0.09654158444794517
d_block_per_expert = 32
default_num_samples = 10
tau = 1.5974624324687077
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 92
