seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-2-bank-marketing"
num_policy = "noisy-quantile"

[optimizer]
type = "Adam"
lr = 0.0010582985358032332

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 960
dropout = 0.0
d_block_per_expert = 32
gating_prior_std = 0.7000900439011009
kl_factor = 0.10278118224157008
default_num_samples = 5
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 18
