seed = 0
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/otto"

[optimizer]
type = "AdamW"
lr = 0.0009644231440909803
weight_decay = 0.0001018292539959896

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 1152
dropout = 0.43722961714791647
d_block_per_expert = 64
default_num_samples = 10
tau = 2.7061593253993164
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 12
