seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-OnlineNewsPopularity"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0012033623043560969
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 1152
dropout = 0.2811798215480079
d_block_per_expert = 32
default_num_samples = 10
tau = 1.400989891776352
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 42
