seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-4-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00038377182436468587
weight_decay = 0.008021145227165813

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 1
d_block = 128
dropout = 0.4493398737607298
d_block_per_expert = 32
adapter = true
gating_type = "sigmoid_adapter"
