seed = 0
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-phoneme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.006031231172810341
weight_decay = 0.015487156510304186

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 1
d_block = 704
dropout = 0.009260897230306986
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 45
