seed = 0
batch_size = 1024
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/covtype2"
num_policy = "noisy-quantile"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.000591318499437962
weight_decay = 0.0003214333936489318

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 4
d_block = 768
dropout = 0.08585940400098814
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 112
