seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-4-analcatdata_supreme"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006089540189838181
weight_decay = 0.0001915589796697941

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 2
d_block = 896
dropout = 0.0
d_block_per_expert = 32
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32

[bins]
n_bins = 48
