seed = 0
function = "_bin.model.main"
n_trials = 100

[sampler]
n_startup_trials = 20

[space]
seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[space.data]
cache = true
path = "data/regression-cat-medium-1-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[space.optimizer]
type = "AdamW"
lr = [
    "_tune_",
    "loguniform",
    0.0001,
    0.005,
]
weight_decay = [
    "_tune_",
    "?loguniform",
    0.0,
    0.0001,
    0.1,
]

[space.model]
arch_type = "tabm-mini"
k = 32

[space.model.backbone]
type = "BMoE"
n_blocks = [
    "_tune_",
    "int",
    1,
    5,
]
d_block = [
    "_tune_",
    "int",
    1024,
    8192,
    512,
]
dropout = [
    "_tune_",
    "?uniform",
    0.0,
    0.0,
    0.5,
]
d_block_per_expert = 256
default_num_samples = 10
tau = [
    "_tune_",
    "uniform",
    0.5,
    3.0,
]
gating_type = "bayesian"
