seed = 0
batch_size = 512
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-large-0-jannis"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.003517722115128695
weight_decay = 0.0025783889059371222

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 2
d_block = 448
dropout = 0.42051997032124044
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 8

[bins]
n_bins = 15
