seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-0-bank-marketing"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.002913036214418611
weight_decay = 0.002021204738290966

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 2
d_block = 704
dropout = 0.29567116555946593
d_block_per_expert = 32
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 24

[bins]
n_bins = 86
