seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-elevators"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0005300304542519945
weight_decay = 0.0

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 1
d_block = 1152
dropout = 0.06645415618173817
d_block_per_expert = 64
default_num_samples = 10
tau = 2.0263473342366303
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 34
