seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-OnlineNewsPopularity"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0006348569656368598
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 4
d_block = 1280
dropout = 0.48069128542699746
d_block_per_expert = 32
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28

[bins]
n_bins = 67
