seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-0-MiamiHousing2016"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0018415133711831
weight_decay = 0.0016677474025313874

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 2
d_block = 1152
dropout = 0.03367145157772091
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 16

[bins]
n_bins = 82
