seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/california"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0007630280066570982
weight_decay = 0.09829848080678066

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 2
d_block = 1152
dropout = 0.4825042400364968
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32

[bins]
n_bins = 79
