seed = 0
batch_size = 128
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-2-cpu_act"
num_policy = "noisy-quantile"

[optimizer]
type = "Adam"
lr = 0.0007341061573979306

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 5
d_block = 960
dropout = 0.0
d_block_per_expert = 64
gating_prior_std = 0.8528890982674436
kl_factor = 0.6296142277817282
default_num_samples = 5
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 28

[bins]
n_bins = 116
