seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-fifa"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0009369837971431558
weight_decay = 0.00037444049000206754

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 1
d_block = 1024
dropout = 0.0
d_block_per_expert = 64
default_num_samples = 10
tau = 1.5225566323488364
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 93
