seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-1-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.001544048854919134
weight_decay = 0.006764042025804386

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 192
dropout = 0.2502543569105147
d_block_per_expert = 32
adapter = true
gating_type = "sigmoid_adapter"
