seed = 0
batch_size = 32
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-wine"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0026164065370985145
weight_decay = 0.06780227021579836

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 4
d_block = 512
dropout = 0.030112735814634917
d_block_per_expert = 64
default_num_samples = 10
tau = 2.1765946740453987
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 12

[bins]
n_bins = 18
