seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/classif-num-medium-1-MagicTelescope"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.0026706734254687407
weight_decay = 0.00016183144605692932

[model]
arch_type = "plain"

[model.backbone]
type = "BMoE"
n_blocks = 1
d_block = 768
dropout = 0.0
d_block_per_expert = 64
default_num_samples = 10
tau = 2.5535079011504016
gating_type = "bayesian"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 20

[bins]
n_bins = 5
