seed = 0
batch_size = 256
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-num-medium-1-pol"
num_policy = "noisy-quantile"

[optimizer]
type = "AdamW"
lr = 0.002674460617782339
weight_decay = 0.002613086668333137

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 2
d_block = 512
dropout = 0.0
d_block_per_expert = 32
adapter = true
gating_type = "sigmoid_adapter"

[model.num_embeddings]
type = "PiecewiseLinearEmbeddings"
d_embedding = 32

[bins]
n_bins = 41
