seed = 0
batch_size = 64
patience = 16
n_epochs = -1
gradient_clipping_norm = 1.0
amp = true

[data]
cache = true
path = "data/regression-cat-medium-0-Mercedes_Benz_Greener_Manufacturing"
cat_policy = "ordinal"

[optimizer]
type = "AdamW"
lr = 0.00012350252620186753
weight_decay = 0.0

[model]
arch_type = "tabm-mini"
k = 32

[model.backbone]
type = "BMoE"
n_blocks = 3
d_block = 1152
dropout = 0.4843164669723356
d_block_per_expert = 64
adapter = true
gating_type = "sigmoid_adapter"
